name = "football-porra-tracker"
main = "src/worker.js"
compatibility_date = "2026-04-03"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "football-porra"
database_id = "b0091f10-46b9-49c7-b3e0-a161eedd9b6d"
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "APP_CACHE"
id = "eacf423d6e2d4711bbfd3ba16aba1610"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "football-porra-media"

[vars]
ENABLE_PREDICTION_QUEUE = "false"

[triggers]
crons = ["0 * * * *"]
