name = "football-porra-tracker"
main = "src/worker.js"
compatibility_date = "2026-04-03"
workers_dev = true
preview_urls = false

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "football-porra"
database_id = "b0091f10-46b9-49c7-b3e0-a161eedd9b6d"
migrations_dir = "./migrations"

[triggers]
crons = ["0 * * * *"]
